# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4cf19024c2536712a43d69f2da4702b229aed70e7f1a8c3888bf4912fda279bfda1dae543c268ace7cafc0514ca5f7dee4b67e02851cdd40c9024e08961ba39c

test:
  secret_key_base: f686fd6f263fd518aa5517d74afac87845b1ac79a0605309c8650a1b08e5292f9d6d40c338c6837b06058d78895d3cf2c4403db8a374ddd6f42aa12975076c4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
